feat: Print full traceback for rust-originated errors (#1435)
Uses `anyhow` to properly format rust errors with their sources when
raising them as python exceptions.

Previously we only showed the top-level line.
E.g. in the included test case we printed
```bash
RuntimeError: Could not read tk2circuit from bytes
```
after this change, it reads
```bash
E       RuntimeError: Could not read tk2circuit from bytes
E       
E       Caused by:
E           0: Error reading package payload in envelope.
E           1: Error reading package payload in envelope.
E           2: OpaqueOp:unknown.unresolved in Node(4) requires extension unknown, but it could not be found in the extension list used during resolution. The available extensions are: arithmetic.conversions, arithmetic.float, arithmetic.float.types, arithmetic.int, arithmetic.int.types, collections.array, collections.borrow_arr, collections.list, collections.static_array, logic, prelude, ptr, tket.bool, tket.debug, tket.futures, tket.global_phase, tket.gpu, tket.guppy, tket.modifier, tket.qsystem, tket.qsystem.random, tket.qsystem.utils, tket.quantum, tket.result, tket.rotation, tket.wasm
```